version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp s3_to_redshift_spark.py s3://gds-assignment-7-tavish/
      - aws s3 cp dags s3://gds-assignment-7-tavish/
  post_build:
    commands:
      - echo "Deployment complete!"