version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip .
  post_build:
    commands:
      - echo "Uploading to S3..."
      - unzip -f deployment_package.zip
      - aws s3 cp s3_to_redshift_spark.py s3://gds-assignment-7-tavish/
      - aws s3 cp dags s3://gds-assignment-7-tavish/
      - echo "Deleting the zip file..."
      - rm -rf deployment_package.zip
      - echo "Deployment complete!"