version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd dags
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip s3_to_redshift_spark.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://gds-assignment-7-tavish/
      - echo "Updating Lambda function via S3..."
      - unzip deployment_package.zip
      - echo "Deleting the zip file..."
      - rm -rf deployment_package.zip
      - echo "Deployment complete!"