version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install zip
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -d deployment_package.zip .
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://gds-assignment-7-tavish/
      - echo "Updating Lambda function via S3..."
      - unzip deployment_package.zip
      - echo "Deleting the zip file..."
      - rm -rf deployment_package.zip
      - echo "Deployment complete!"